
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cdf.redhat.com
  resources:
  - codigofontes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cdf.redhat.com
  resources:
  - codigofontes/finalizers
  verbs:
  - update
- apiGroups:
  - cdf.redhat.com
  resources:
  - codigofontes/status
  verbs:
  - get
  - patch
  - update
